#!/usr/bin/env python3

import argparse
import json
import sys
from datetime import datetime, timezone

from youtube_transcript_api import YouTubeTranscriptApi


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--video-id", required=True)
    parser.add_argument("--languages", default="en,en-US")
    args = parser.parse_args()

    languages = [part.strip() for part in args.languages.split(",") if part.strip()]

    try:
        transcript = YouTubeTranscriptApi().fetch(args.video_id, languages=languages or ["en", "en-US"])
    except Exception:
        return 1

    text = " ".join(snippet.text.strip() for snippet in transcript if getattr(snippet, "text", "").strip()).strip()
    if not text:
        return 1

    payload = {
        "text": text,
        "languageCode": getattr(transcript, "language_code", "") or "",
        "languageName": getattr(transcript, "language", "") or "",
        "isAutoGenerated": bool(getattr(transcript, "is_generated", False)),
        "fetchedAt": datetime.now(timezone.utc).isoformat(),
    }
    sys.stdout.write(json.dumps(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
