from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse
import json
from datetime import datetime, timezone

from youtube_transcript_api import YouTubeTranscriptApi


class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        video_id = (params.get("videoId") or [""])[0].strip()
        languages = [value.strip() for value in params.get("language", []) if value.strip()]
        if not video_id:
            return self._json({"error": "videoId is required"}, 400)

        try:
            transcript = YouTubeTranscriptApi().fetch(video_id, languages=languages or ["en", "en-US"])
        except Exception:
            return self._json({"error": "transcript unavailable"}, 404)

        text = " ".join(
            snippet.text.strip() for snippet in transcript if getattr(snippet, "text", "").strip()
        ).strip()
        if not text:
            return self._json({"error": "transcript unavailable"}, 404)

        return self._json(
            {
                "text": text,
                "languageCode": getattr(transcript, "language_code", "") or "",
                "languageName": getattr(transcript, "language", "") or "",
                "isAutoGenerated": bool(getattr(transcript, "is_generated", False)),
                "fetchedAt": datetime.now(timezone.utc).isoformat(),
            },
            200,
        )

    def _json(self, payload, status):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
